[package]
name = "hm-template"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Felix Schladt <https://github.com/FelixSchladt>"]
license = "AGPL"
description = "Unofficial Template for Munich University of Applied Science (HM)"
repository = "https://github.com/FelixSchladt/hm-template
keywords = ["HM", "hm", "thesis", "Modularbeit", "Hochschule", "MÃ¼nchen", "Munich"]
categories = ["paper", "thesis", "report"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"